IF( WIN32 )
 SET( CPACK_GENRATOR                             "NSIS"                        )
 SET( CPACK_NSIS_PACKAGE_NAME                    install_${CMAKE_PROJECT_NAME} )
 SET( CPACK_NSIS_MODIFY_PATH                     ON                            )
 SET( CPACK_PACKAGING_INSTALL_PREFIX             ${INSTALL_LOCATION}           )
 SET( CPACK_PACKAGE_INSTALL_DIRECTORY            ${CMAKE_PROJECT_NAME}         )
 SET( CPACK_NSIS_ENABLE_UNINSTALL_BEFORE_INSTALL OFF                           )
 SET( CPACK_NSIS_MODIFY_PATH                     ON                            )
ENDIF() 

IF( UNIX )
  SET( CPACK_GENERATOR                 ${GENERATOR}                              )
  SET( CPACK_PACKAGING_INSTALL_PREFIX  ${INSTALL_LOCATION}/${CMAKE_PROJECT_NAME} )
  SET( CPACK_RPM_PACKAGE_AUTOREQ       YES                                       )
  SET( CPACK_RPM_PACKAGE_AUTOPROV      YES                                       )
  SET( CPACK_RPM_SPEC_MORE_DEFINE      "%define _build_id_links none"            )
  SET( CPACK_DEBIAN_PACKAGE_SHLIBDEPS  ON                                        )
  SET( CPACK_DEBIAN_PACKAGE_MAINTAINER "Overcaster"                              )
  SET( CPACK_PACKAGE_INSTALL_DIRECTORY ${CMAKE_PROJECT_NAME}                     )
ENDIF() 

SET( CMAKE_INSTALL_RPATH "${CPACK_PACKAGING_INSTALL_PREFIX}/${LIB_DIR}" )
SET( CMAKE_INSTALL_RPATH_USE_LINK_PATH TRUE                             )
SET( CPACK_RESOURCE_FILE_LICENSE ${CMAKE_SOURCE_DIR}/LICENSE            )
SET( CPACK_PACKAGE_VERSION ${PROJECT_VERSION}                           )
SET( CPACK_PACKAGE_NAME    ${CMAKE_PROJECT_NAME}                        )

INCLUDE( CPack )
