FUNCTION( MESSAGE )

  IF( ARGV )
    LIST( GET       ARGV 0 MESSAGE_TYPE )
    LIST( REMOVE_AT ARGV 0              )

    IF( "${MESSAGE_TYPE}" STREQUAL FATAL_ERROR )
      _MESSAGE( FATAL_ERROR "${ARGV}" )

    ELSEIF( "${MESSAGE_TYPE}" STREQUAL SEND_ERROR )
      _MESSAGE( SEND_ERROR "${ARGV}" )

    ELSEIF( "${MESSAGE_TYPE}" STREQUAL WARNING )
      _MESSAGE( WARNING "${ARGV}" )

    ELSEIF( "${MESSAGE_TYPE}" STREQUAL AUTHOR_WARNING )
      _MESSAGE( AUTHOR_WARNING "${ARGV}" )

    ELSEIF( "${MESSAGE_TYPE}" STREQUAL "INFO" )
      LIST( GET ARGV 0 USER_MOD )
      IF( "${USER_MOD}" STREQUAL "ON" OR "${USER_MOD}" STREQUAL "TRUE" )
        LIST     ( REMOVE_AT ARGV 0 )
        _MESSAGE ( STATUS "${ARGV}" )
      ELSEIF( NOT "${USER_MOD}" STREQUAL "OFF" AND NOT "${USER_MOD}" STREQUAL "FALSE" )
        _MESSAGE( STATUS "${ARGV}" )
      ENDIF()
    ENDIF()
  ELSE()
    _MESSAGE( STATUS "" )
  ENDIF()
ENDFUNCTION()
